modmap:
  - name: Global
    remap:
      CapsLock: Ctrl_L
      # TODO: 正確なキーを指定する
      # https://github.com/emberian/evdev/blob/1d020f11b283b0648427a2844b6b980f1a268221/src/scancodes.rs#L26-L572
      # Fn: CapsLock
      # Ctrl_R: Fn
