# NOTE: 変数名とキーコードの対応表: https://github.com/emberian/evdev/blob/1d020f11b283b0648427a2844b6b980f1a268221/src/scancodes.rs#L26-L572
# ＊対応表で紐付けられているキー名とキーコードは、環境によってマッチしないので、xev コマンドなどを使いキーコードを確認すること
# https://symfoware.blog.fc2.com/blog-entry-2677.html
modmap:
  - name: Global
    remap:
      CapsLock: Ctrl_L
      KatakanaHiragana: Alt_R
      Muhenkan: Grave # Muhenkan: HankakuZenkaku
      Henkan: Grave # Henkan: HankakuZenkaku
  # TODO: なんか動かん。。。
  # GNOME Wayland じゃなくて、X11 の方で Google chrome が表示されてるのおかしい気がする？
  # https://github.com/k0kubun/xremap#x11-1
  #
  # Error Log
  # GnomeClient#connect() failed: I/O error: No such file or directory (os error 2)
  # application-client: GNOME (supported: false)
  #
  # - name: Google Chrome
  #   application:
  #     only: Google-chrome
  #   remap:
  #     Alt_L: Ctrl_L
  #     KatakanaHiragana: Ctrl_R
