modmap:
  - name: Global
    remap:
      CapsLock: Ctrl_L
      KatakanaHiragana: Alt_R
      # TODO: システム設定 > キーボード > 入力ソース の日本語(Mozc)のキー設定にて、
      # 無変換・変換を IME 無効・ IME 有効に設定しているが、これも xremap 上で管理したい。
      # Muhenkan: Disable IME
      # Henkan: Enable IME
  # TODO: なんか動かん。。。
  # GNOME Wayland じゃなくて、X11 の方で Google chrome が表示されてるのおかしい気がする？
  # https://github.com/k0kubun/xremap#x11-1
  #
  # Error Log
  # GnomeClient#connect() failed: I/O error: No such file or directory (os error 2)
  # application-client: GNOME (supported: false)
  #
  # - name: Google Chrome
  #   application:
  #     only: Google-chrome
  #   remap:
  #     Alt_L: Ctrl_L
  #     KatakanaHiragana: Ctrl_R
